#!/bin/bash

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

# zsh config
zsh_config(){
  cd ~
  mkdir -p .antigen
  echo "Setting up antigen, just be patients."
  curl -L git.io/antigen -o .antigen/antigen.zsh &>/dev/null
  echo "Setting dircolors."
  curl -L https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-universal -o ~/.dir_colors &>/dev/null
  echo "Update .zshrc file."
  curl -LO https://raw.githubusercontent.com/BruceLEO1969/vps2arch/master/.zshrc &>/dev/null
  echo "zsh_config finished."
}

# tmux_config
tmux_config(){
  rm -rf .tmux
  git clone https://github.com/BruceLEO1969/.tmux.git &>/dev/null
  ln -s -f .tmux/.tmux.conf
  cp .tmux/.tmux.conf.local .
  echo "tmux setup finished."
}

# vim_config
vim_config(){
  curl https://raw.githubusercontent.com/BruceLEO1969/spf13-vim/3.0/bootstrap.sh -sL -o - | sh
}

# softwares install
install(){
  yaourt -Sy ccat --noconfirm &>/dev/null
}

# main function
main(){
  zsh_config
  tmux_config
  vim_config
  install
}

main
zsh
